name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent and Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo -i
            cd /var/www

            # Clone repo if it doesn't exist
            if [ ! -d "api_ec2.git" ]; then
              git clone https://github.com/ekrambd/api_ec2.git
            fi

            cd api_ec2

            git pull origin main

            # Set up .env if missing
            if [ ! -f ".env" ]; then
              cp .env.example .env
              composer install --no-dev --optimize-autoloader
              php artisan key:generate
            fi

            php artisan migrate
            chmod -R ugo+rw storage/logs
            chmod -R ugo+rw storage/framework/
            chmod -R 775 storage bootstrap/cache
          EOF
